baseURL: "https://www.designerdo.nl/"
languageCode: "en-us"
title: "designerDo"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/ID15CF7/hugo-theme-novela-deisgnerdo"
paginate: 6
social:
  twitter: "https://twitter.com/skruvmuq"
  github: "https://github.com/ID15CF7"
  instagram: "#"
  linkedin: "https://www.linkedin.com/in/hidde-ploysiri/"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
